### PR TITLE
Insure a bookmark isn't matched multiple times when other bookmarks have the same prefix 

### PR DESCRIPTION
**Pull request by cslux**
Consider the following two bookmarks:

... All thrashed emails older than 2 month
... All thrashed emails

Before this fix the first one would be truncated to the length of the
second one.

----

#

### CODE REVIEW

**Comment by agpchil** [comment]
I think this may not work in other cases but I cannot test it.

Can you check what happens if `title` already contains special characters that could be interpreted as a valid or invalid regex pattern?

**Comment by cslux** [comment]
You are right! We could store the last `search-forwared` point and continue from there. What do you think?

**Comment by agpchil** [comment]
I'm not sure that using a global var for this is the right approach.

From the elisp manual (search-forward):
> If the search is successful, search-forward leaves point immediately after the last character in the target string.

So maybe it should be enough to check the char at point, after the `search-forward`, to ensure you reached the end of line.

Can you try something like this using, for example, `(eolp)`?

```emacs-lisp
 (when (and (search-forward title nil t) (eolp))
```

Does it work?

**Comment by cslux** [comment]
Unfortunately  not. This is because of `mu4e-maildirs-extension-bookmark-format`.

**Comment by cslux** [comment]
@agpchil Here is another possibility ce4bac6. Collect all the bookmark points first and create a list of cons-cells ((bm . point) ...) and pass each cons-cell to `mu4e-maildirs-extension-bm-update`

**Comment by agpchil** [comment]
Indeed. This is trickier!
I'm not sure if your changes works for all cases but if you want I'll merge it as it is. (The bookmarks feature was experimental to begin with)

**Comment by cslux** [comment]
Please merge! I'll watch the project, if someone runs into a problem with that fix I'll try to provide a fix for it. 

Thanks!

**Comment by agpchil** [comment]
That would be great! ;)
Merged.
Thank you and sorry for the delay.

**Pull request merged**
